# This rule is not used by the project first-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the mygroup.operator.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: first-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: mykind-editor-role
rules:
- apiGroups:
  - mygroup.operator.com
  resources:
  - mykinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.operator.com
  resources:
  - mykinds/status
  verbs:
  - get
